export default [
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },   {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },   {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },

    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },   
    {
        tipePenerima:'individu',
        nama:'Nurul Atikah',
        email:'nurul21@gmail.com',
        npwp:'81932497140',
        provinsi:'jawa barat',
        kabupaten:'indramayu',
        kecamatan:'haurgeulis',
        kelurahan:'mekarjati',
        rt:'02',
        rw:'02',
        alamat:'jalan siliwangi No.23',
        keterangan:'active'  
    },

   
]