export default [
    {
        kodeBank:'002',
        namaBank:'BANK MANDIRI',
        cabang:'Umbulharjo',
        noRekening:'41352463894958902',
        namaNoRekening:'Abdul Rahman',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'004',
        namaBank:'BANK BRI',
        cabang:'Nologaten',
        noRekening:'4134267878799889',
        namaNoRekening:'Abdan Rabbani',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'002',
        namaBank:'BANK MANDIRI',
        cabang:'Umbulharjo',
        noRekening:'41352463894958902',
        namaNoRekening:'Abdul Rahman',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'004',
        namaBank:'BANK BRI',
        cabang:'Nologaten',
        noRekening:'4134267878799889',
        namaNoRekening:'Abdan Rabbani',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'002',
        namaBank:'BANK MANDIRI',
        cabang:'Umbulharjo',
        noRekening:'41352463894958902',
        namaNoRekening:'Abdul Rahman',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'004',
        namaBank:'BANK BRI',
        cabang:'Nologaten',
        noRekening:'4134267878799889',
        namaNoRekening:'Abdan Rabbani',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'002',
        namaBank:'BANK MANDIRI',
        cabang:'Umbulharjo',
        noRekening:'41352463894958902',
        namaNoRekening:'Abdul Rahman',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'004',
        namaBank:'BANK BRI',
        cabang:'Nologaten',
        noRekening:'4134267878799889',
        namaNoRekening:'Abdan Rabbani',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'002',
        namaBank:'BANK MANDIRI',
        cabang:'Umbulharjo',
        noRekening:'41352463894958902',
        namaNoRekening:'Abdul Rahman',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'004',
        namaBank:'BANK BRI',
        cabang:'Nologaten',
        noRekening:'4134267878799889',
        namaNoRekening:'Abdan Rabbani',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'002',
        namaBank:'BANK MANDIRI',
        cabang:'Umbulharjo',
        noRekening:'41352463894958902',
        namaNoRekening:'Abdul Rahman',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'004',
        namaBank:'BANK BRI',
        cabang:'Nologaten',
        noRekening:'4134267878799889',
        namaNoRekening:'Abdan Rabbani',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'002',
        namaBank:'BANK MANDIRI',
        cabang:'Umbulharjo',
        noRekening:'41352463894958902',
        namaNoRekening:'Abdul Rahman',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'004',
        namaBank:'BANK BRI',
        cabang:'Nologaten',
        noRekening:'4134267878799889',
        namaNoRekening:'Abdan Rabbani',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
        {
        kodeBank:'002',
        namaBank:'BANK MANDIRI',
        cabang:'Umbulharjo',
        noRekening:'41352463894958902',
        namaNoRekening:'Abdul Rahman',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
    {
        kodeBank:'004',
        namaBank:'BANK BRI',
        cabang:'Nologaten',
        noRekening:'4134267878799889',
        namaNoRekening:'Abdan Rabbani',
        keterangan:'valid',
        tipeRekening:'bos',  
    },
]