stages:
  - build
  - test
  - deploy

image: docker:19.03.12
services:
  - name: docker:19.03.12-dind
    command: ["--experimental"]

variables:
 RANCHER_URL_DEV: "https://rancher.erkam.cronos.co.id/v3"
 RANCHER_TOKEN_DEV: "token-cxsqt:5m5l4zbb8bvs5t247nw9vwb54blzc5lmzw6mb7m2mrxt7ccnlc94rb --context c-zlbdm:p-xvpj9"
 RANCHER_URL_STAGING: "https://rancher.erkam.cronos.co.id/v3"
 RANCHER_TOKEN_STAGING: "token-cxsqt:5m5l4zbb8bvs5t247nw9vwb54blzc5lmzw6mb7m2mrxt7ccnlc94rb --context c-8r7st:p-9n8j6"
#  RANCHER_URL_PRO: "https://rancher.erkam.cronos.co.id/v3"
#  RANCHER_TOKEN_PRO: "token-cxsqt:5m5l4zbb8bvs5t247nw9vwb54blzc5lmzw6mb7m2mrxt7ccnlc94rb --context c-c4kx6:p-h46g4"
#  RANCHER_URL_LATIHAN: "https://rancher.erkam.cronos.co.id/v3"
#  RANCHER_TOKEN_LATIHAN: "token-cxsqt:5m5l4zbb8bvs5t247nw9vwb54blzc5lmzw6mb7m2mrxt7ccnlc94rb --context c-f7rvq:p-fjq74"
 IMAGE: "$CI_REGISTRY_IMAGE"
 IMAGE_VERSION: "$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID"
 IMAGE_TAGS: "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
 DOCKER_TLS_CERTDIR: "/certs"
 DOCKER_DRIVER: overlay2
 DOCKER_BUILDKIT: "1"
 DOCKER_CLI_EXPERIMENTAL: enabled
 BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64

before_script:
    - time=$(date +%Y%m%d%H%M)

build_docker:
  stage: build
  script:
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker info
    - docker context create tls-environment
    - docker buildx create --name mybuilder --use tls-environment
    # - cp src/environments/environment.$CI_COMMIT_BRANCH.ts src/environments/environment.prod.ts
    - docker buildx build -t $IMAGE_VERSION --cache-from=type=registry,ref=$IMAGE:cache --cache-to=type=registry,ref=$IMAGE:cache,mode=max --push --progress=plain .
  only:
  - branches

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

sast:
  stage: test

code_quality:
  stage: test
  variables:
    REPORT_FORMAT: html
    CONTAINER_TIMEOUT_SECONDS: "3600"
    ENGINE_MEMORY_LIMIT_BYTES: "2000000000"
#    CODECLIMATE_DEBUG: "0"
    
  artifacts:
    expose_as: 'Web Code Quality Report'
    paths: [gl-code-quality-report.html]
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_COMMIT_BRANCH'      
 
     
build_docker_release:
  stage: build
  script:
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker info
    - docker context create tls-environment
    - docker buildx create --name mybuilder --use tls-environment
    # - cp src/environments/environment.release.ts src/environments/environment.prod.ts
    - docker buildx build -t $IMAGE_TAGS --cache-from=type=registry,ref=$IMAGE:cache --cache-to=type=registry,ref=$IMAGE:cache,mode=max --push --progress=plain  .
  only:
    - tags

build_docker_latihan:
  stage: build
  script:
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker info
    - docker context create tls-environment
    - docker buildx create --name mybuilder --use tls-environment
    # - cp src/environments/environment.latihan.ts src/environments/environment.prod.ts
    - docker buildx build -t $IMAGE_TAGS-latihan --cache-from=type=registry,ref=$IMAGE:cache --cache-to=type=registry,ref=$IMAGE:cache,mode=max --push --progress=plain  .
  only:
    - tags

deploy_devel:
  stage: deploy
  image: grumblex/rancher-cli-kubectl
  script:
    - rancher login  --token=$RANCHER_TOKEN_DEV  --skip-verify $RANCHER_URL_DEV
   # - rancher kubectl apply -f env-$CI_COMMIT_BRANCH.yaml
    - rancher kubectl -n $CI_COMMIT_BRANCH  set image deployment $CI_PROJECT_NAME $CI_PROJECT_NAME=$IMAGE_VERSION
    - rancher kubectl -n $CI_COMMIT_BRANCH rollout status  deployments $CI_PROJECT_NAME
  only:
      - dev
  environment:
   name: development

deploy_staging:
  stage: deploy
  image: grumblex/rancher-cli-kubectl
  script:
    - rancher login --token=$RANCHER_TOKEN_STAGING  $RANCHER_URL_STAGING  --skip-verify
 #   - rancher kubectl -n $CI_COMMIT_BRANCH  apply -f env-$CI_COMMIT_BRANCH.yaml
    - rancher kubectl -n $CI_COMMIT_BRANCH  set image deployment $CI_PROJECT_NAME $CI_PROJECT_NAME=$IMAGE_VERSION
    - rancher kubectl -n $CI_COMMIT_BRANCH rollout status  deployments $CI_PROJECT_NAME
  only:
    - staging
  environment:
   name: staging


deploy_production_release:
  stage: deploy
  image: grumblex/rancher-cli-kubectl
  script:
    - rancher login --token=$RANCHER_TOKEN_PRO  $RANCHER_URL_PRO  --skip-verify
#    - rancher kubectl -n $CI_COMMIT_BRANCH  apply -f env-$CI_COMMIT_BRANCH.yaml
    - rancher kubectl -n release  set image deployment $CI_PROJECT_NAME $CI_PROJECT_NAME=$IMAGE_TAGS
    - rancher kubectl -n release rollout status  deployments $CI_PROJECT_NAME
  only:
    - tags
  environment:
   name: release

deploy_production_latihan:
  stage: deploy
  image: grumblex/rancher-cli-kubectl
  script:
    - rancher login --token=$RANCHER_TOKEN_LATIHAN  $RANCHER_URL_LATIHAN  --skip-verify
#    - rancher kubectl -n $CI_COMMIT_BRANCH  apply -f env-$CI_COMMIT_BRANCH.yaml
    - rancher kubectl -n latihan  set image deployment $CI_PROJECT_NAME $CI_PROJECT_NAME=$IMAGE_TAGS-latihan
    - rancher kubectl -n latihan rollout status  deployments $CI_PROJECT_NAME
  only:
    - tags
  environment:
   name: latihan
